# Error handling in Python11

# Example oof dividing two numbers with error handling1112
def divide_numbers(x, y):
    try:
        result = x / y
        print("The result of division is:", result)
    except ZeroDivisionError as e:
        print("Error:", e)
    except Exception as e:
        print("An error occurred:", e)

# Test the divide_numbers function with potential error1
divide_numbers(10, 1)  # No error, result is printed
divide_numbers(10, 0)  # ZeroDivisionError, error message is printed
divide_numbers(10, '2')  # TypeError, error message is printed
